name: tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - run: npm install
    - run: npm test
